services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskforce
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/taskforce

  frontend: # <- now properly inside services
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - backend

volumes:
  db_data:
