version: '3.9'

services:
  frontend:
    build: .
    ports:
      - '8080:80'
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=taskforce
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: taskforce-db-1
    environment:
      POSTGRES_DB: taskforce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
